### ISSUE TITLE
Can it work with dynamic marker ?

### ISSUE THREAD

**Issue by MinhNQ90** [bramus/react-native-maps-directions#1]
Hi,
Can and How i use dynamic marker with your directions ?
Example: After i search and set markers for search locations.
Thank you.

**Comment by bramus** [comment]
Yes it can work with a dynamic marker. Just like you pass a coordinate to your `MapView.Marker` component, pass in an origin coordinate _(most likely your current location)_ and a destination coordinate to the `MapViewDirections` component.

**Comment by MinhNQ90** [comment]
Hi Bramus,
i try same as you suggest but i got this error
![image](https://user-images.githubusercontent.com/33272530/33053954-f6878d70-cea8-11e7-9307-c83e36bb7a94.png)
And this is my source code
`const coordinates = [
  {
    latitude: 0,
    longitude: 0,
  },
  {
    latitude: 0,
    longitude: 0,
  },
];`
`<MapView.Marker coordinate={coordinates[0]} />
				<MapView.Marker coordinate={coordinates[1]} />
				<MapViewDirections origin={coordinates[0]} destination={coordinates[1]} apikey={GOOGLE_MAPS_APIKEY} strokeWidth={3} strokeColor="hotpink" />`
`onPress={(data, details = null) => {    // 'details' is provided when fetchDetails = true
					if(data.description != ""){
						this.state.start = data.description;
						coordinates[0].latitude = details.geometry.location.lat;
						coordinates[0].longitude = details.geometry.location.lng;`
How can i solve this issue ?

**Comment by arma7x** [comment]
Does doing this will not violate google maps policy? I'm using google map free subscription plan
