### ISSUE TITLE
Support waypoints

### ISSUE THREAD

**Issue by outis10** [bramus/react-native-maps-directions#10]
Hi, are you planning to extend  this component to support waypoint to create  the route with array of points.

Thanks in advanced!!!

**Comment by bramus** [comment]
Added in 1.4.0

<img width="545" alt="screen shot 2018-01-07 at 00 14 41" src="https://user-images.githubusercontent.com/213073/34645046-4fa4fa18-f344-11e7-8e62-5a95009c9c06.png">

**Comment by imarem** [comment]
Boss!!

**Comment by babelom** [comment]
Sorry bro, but can you explain or show a piece of code please because I've try so many things with "waypoints" but nothing happened ... ?

Thank you very much ..
