### ISSUE TITLE
calculating distance in metres

### ISSUE THREAD

**Issue by vrinch** [bramus/react-native-maps-directions#101]
great package, however, I would like to know if its possible to calculate and display distance in metres or have decimal in kilometres 
for example 
200 metres
0.2km

same for duration, If its possible to have then in hours

many thanks

**Comment by dcosmin2003** [comment]
You can do it like this:

`
<MapViewDirections
    onReady={result => {
        let distanceString = (result.distance < 1 ? result.distance * 1000 + ' m' : Math.round(this.props.global?.initialDistanceToScooter * 10) / 10 + ' km');
    }}
/>
`
