### ISSUE TITLE
Warning: Failed prop type: The prop `apikey` is marked as required in `MapViewDirections`, but its value is `undefined`.

### ISSUE THREAD

**Issue by gitMomo** [bramus/react-native-maps-directions#102]
I get this warning (but it block my app) : 

**Warning: Failed prop type: The prop `apikey` is marked as required in `MapViewDirections`, but its value is `undefined`.**

`<MapViewDirections
    destination={destination}
    origin={origin}
    onReady={onReady}
    apiKey="my_api_key"
    strokeWidth={3}
    strokeColor= "#222"
  />`

**Comment by aflansburg** [comment]
You have to obtain a Google Cloud Platform API key and enable the Directions API.

![image](https://user-images.githubusercontent.com/10121043/63948695-b847b100-ca3e-11e9-9f02-45f51fc2a414.png)

**Comment by bramus** [comment]
The prop is `apikey`, not `apiKey` which you are using.
