### ISSUE TITLE
Polyline does not show route map accurately.

### ISSUE THREAD

**Issue by ppv94** [bramus/react-native-maps-directions#108]
Route map between waypoints are shown but they are not accurate. straight lines appear in-between location to location. how can we get the accurate route map between multiple points.
![Screen Shot 2019-10-17 at 7 33 08 PM](https://user-images.githubusercontent.com/28724702/67016092-3eb27200-f115-11e9-8b51-af794dfee1d8.png)

**Comment by bramus** [comment]
For performance reasons the overview polyline is drawn. If you want the more accurate polyline, which contains more legs, to be drawn set `precision` to `high`.

This feature was [added in 1.7.3](https://github.com/bramus/react-native-maps-directions/blob/master/CHANGELOG.md#173---2019-10-02).

**Comment by ppv94** [comment]
it works thanks @bramus
