### ISSUE TITLE
Add option to split waypoints to multiple routes if exceeding waypoint limit

### ISSUE THREAD

**Issue by capJavert** [bramus/react-native-maps-directions#109]
Directions API has limit of 10 or 25 waypoints per route. So `waypoints` array is size is limited to those numbers.

There is a workaround where you can use multiple `MapViewDirections` components with connected origin/destination which appear to the user as one route. I have implemented this logic inside my project.

My idea is to add `boolean` type prop `splitWaypoints` or similar that will automatically do this under the hood because I think many people have and would have a need for this.

I am open to submit pull request and implement dis if there is interest,
What do you think? @bramus

**Comment by bramus** [comment]
Looks nice, although I don't see any mention of waypoints being limited, only the fact that [the Directions API call will cost more when exceeding 10 waypoints](https://developers.google.com/maps/documentation/directions/intro#Waypoints).

> Caution: Requests using 10 or more waypoints, or waypoint optimization, are billed at a higher rate.

There is some limit though, as the length of URLs are limited … but that's not immediately linked to a number of waypoints

> URLs must be properly encoded to be valid and are limited to 8192 characters for all web services. Be aware of this limit when constructing your URLs.

A question: this will mean that `optimizeWaypoints` will not be able to work right, as you're splitting out the waypoints yourself?

**Comment by capJavert** [comment]
Advanced package is limited to [25 waypoints](https://developers.google.com/maps/documentation/directions/usage-and-billing#directions-advanced)
> More than 10 waypoints (between 11 and 25)

> A question: this will mean that optimizeWaypoints will not be able to work right, as you're splitting out the waypoints yourself?

I would just render multiple `MapViewDirections` so each set of waypoints would get optimised separately. I think this is an ok trade-off for this functionality.

**Comment by bramus** [comment]
Aha, wasn't aware of that limit. Looks like a good feature to me! 👍
