### ISSUE TITLE
how to draw direction between multiple points ?

### ISSUE THREAD

**Issue by rAnAaRsl** [bramus/react-native-maps-directions#11]
how can i draw line between multiple points on map instead of origin to destination actually i am working on tracking application where i have multiple locations from where user passes so how can i draw it between multiple points ?

**Comment by bramus** [comment]
Use [the `waypoints` prop](https://github.com/bramus/react-native-maps-directions#props) for this, which was [recently added](https://github.com/bramus/react-native-maps-directions/issues/10)
