### ISSUE TITLE
Directions not rendered on iOS if wrapped in a View

### ISSUE THREAD

**Issue by koo27** [bramus/react-native-maps-directions#113]
I have been struggling on this bug for a while, and I finally found out that if you wrap MapViewDirections in a View, it doesn't work on iOS (i.e. it doesn't not render the polylines)
Instead on Android works perfectly fine in any case.

Tested on these versions:
```
"react-native": "0.60.4",
"react-native-maps": "^0.25.0",
"react-native-maps-directions": "^1.7.3"
```

**Comment by bramus** [comment]
This is expected behavior: react-native-maps-directions will eventually yield a react-native-maps Polyline component. As per react-native-maps requirement, such a component **must** be a direct child of a MapView component.
