### ISSUE TITLE
I am trying to establish a line between two locations in google maps using react-native.but i am getting "react-native-maps-directions Error on GMAPS route request Unknown error." Here is my code

### ISSUE THREAD

**Issue by santhoshreddysudaksha** [bramus/react-native-maps-directions#115]
import React , { Component } from 'react';
import { Dimensions, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';
import MapViewDirections from 'react-native-maps-directions';

const GOOGLE_MAPS_APIKEY = "...";
const origin = {latitude: 15.846812, longitude: 80.891340, latitudeDelta: 0.0622, longitudeDelta: 0.0421};
const destination = {latitude: 15.750875, longitude: 81.018389, latitudeDelta: 0.0622, longitudeDelta: 0.0421};

class RNMapsDirectionsExample extends Component{
  render(){
    return(
      console.log('orgin' ,{origin}),
      console.log('destination', {destination}),
       <MapView initialRegion={
        {
              latitude: 15.846812, 
              longitude: 80.891340,
              latitudeDelta: 0.0622,
              longitudeDelta: 0.0421}
        }>
        <MapViewDirections
              origin={origin}
              destination={destination}
              apikey={GOOGLE_MAPS_APIKEY}
        />
        </MapView>

    );
  }
}

const styles = StyleSheet.create({
  mapContainer: {
    width: "100%",
    height: 200,
    marginTop: 20,
    flex:1
  },
  map: {
    width: "100%",
    height: "100%",
    flex:1
  }
});

export default RNMapsDirectionsExample;

**Comment by bramus** [comment]
Please verify that you have [a valid Google Maps Directions API Key](https://developers.google.com/maps/documentation/directions/get-api-key), and that Billing is enabled for your account.

**Comment by santhoshreddysudaksha** [comment]
We Are using a valid Google Maps Directions API Key and the Billing Is also enabled.

**Comment by Nsengiyunva** [comment]
I am facing the same issue too with a valid API key and billing enabled.

**Comment by bramus** [comment]
@santhoshreddysudaksha I've tested my example app with the coordinates you've provided and the Google Directions API cannot route between those coordinates.

There is no `error_message` returned by the API, but there is a `status` field that says `"ZERO_RESULT"`. I'll update this project to return the `status`, so that the error is more descriptive.
