### ISSUE TITLE
where to find the map API's which is use to navigation  in river and  ocean ???

### ISSUE THREAD

**Issue by santhoshreddysudaksha** [bramus/react-native-maps-directions#118]
I am creating a project in react-native in which I want navigation inside water. I tried using google API but it is not working as google API is only for the land route. But, I want an API that I can use for navigation inside water. Please tell me the API for navigation inside the water.

**Comment by bramus** [comment]
This component uses the Google Maps Directions API. Limitations imposed by that API are therefore also limitations of this component.

**Comment by santhoshreddysudaksha** [comment]
> This component uses the Google Maps Directions API. Limitations imposed by that API are therefore also limitations of this component.

That's the reason we are asking  for any alternative reader then google mapS API
