### ISSUE TITLE
Waypoint dont work

### ISSUE THREAD

**Issue by zapcriativo** [bramus/react-native-maps-directions#123]
Hi, 

I try to insert waypoints, buy dont work... 

Can you help me?

My map code

`  <MapView
            initialRegion={{
              latitude: userLat,
              longitude: userLon,
              latitudeDelta: 0.005,
              longitudeDelta: 0.001
            }}
            style={{
              height: SCREEN_HEIGHT - this.props.CURRENT_PANEL_BOTTOM_SIZE
            }}
            showsTraffic={true}
            ref={ref => { this.map = ref; }}
            customMapStyle={mapStyle}
            rotateEnabled={false}
            zoomEnabled={true}
            showsUserLocation
          >

            <MapView.Marker coordinate={{ latitude: userLat, longitude: userLon }} pinColor={'#849758'} title={'Motorista'} description={'Você está aqui'} />

            
            <MapView.Marker
              coordinate={{
                latitude: this.props.trip_data_socket[0].trip_start_location.coordinates[0],
                longitude: this.props.trip_data_socket[0].trip_start_location.coordinates[1],
              }}
              pinColor={'#484873'} title={'Passageiro'}
              description={'Passageiro Esperando'} />

            <MapView.Marker
              coordinate={{
                latitude: this.props.trip_data_socket[0].trip_end_location.coordinates[0],
                longitude: this.props.trip_data_socket[0].trip_end_location.coordinates[1],
              }}
              pinColor={'#542f42'} title={'Destino'}
              description={'Local de Destino da Viagem'} />

            <MapViewDirections
              origin={{
                latitude: userLat,
                longitude: userLon
              }}
              waypoints={{
                latitude: this.props.trip_data_socket[0].trip_start_location.coordinates[0],
                longitude: this.props.trip_data_socket[0].trip_start_location.coordinates[1],
              }}
              destination={{
                latitude: this.props.trip_data_socket[0].trip_end_location.coordinates[0],
                longitude: this.props.trip_data_socket[0].trip_end_location.coordinates[1],
              }}
              optimizeWaypoints={true}
              apikey={config.GOOGLE_MAPS_KEY}
              language='pt_BR'
              mode='DRIVING'
              strokeWidth={3}
              strokeColor="#000"
              onStart={(params) => {
                console.log(`Started routing between "${params.origin}" and "${params.destination}"`);
              }}
              onReady={result => {

                this.setState({ tempo_entre_pontos: result.duration })
                this.setState({ distancia_entre_pontos: parseFloat(result.distance) })

                console.log('Distance:' + result.distance + 'km')
                console.log('Duration:' + result.duration + 'min.')

                // this.mapView.fitToCoordinates(params.origin, {
                //   edgePadding: {
                //     right: (width / 20),
                //     bottom: (height / 20),
                //     left: (width / 20),
                //     top: (height / 20),
                //   }
                // });
              }}
              onError={(errorMessage) => {
                // console.log('GOT AN ERROR');
              }}
            />

          </MapView>`

**Comment by bramus** [comment]
You're passing an object into the `waypoints` prop. It should be an array of objects, like so:

```
          waypoints={[{
            latitude: this.props.trip_data_socket[0].trip_start_location.coordinates[0],
            longitude: this.props.trip_data_socket[0].trip_start_location.coordinates[1],
          }]}
```
