### ISSUE TITLE
onReady issue

### ISSUE THREAD

**Issue by 14076156deiefyp** [bramus/react-native-maps-directions#13]
I don't know why if I want to set variables in onReady, it will goes to an infinity loop, however if I just use console.log, it is alright, here is the code.  The code should not affected the origin and destinaiton.

        <MapViewDirections
            origin={{latitude:this.state.startLatitude,longitude:this.state.startLongitude}}
            destination={{latitude:this.state.endLatitude,longitude:this.state.endLongitude}}
            mode='driving'
            language='en'
            strokeWidth={4}
            strokeColor="black"
            onReady={(result) => {
                 //this.setDistance(result.distance,result.duration_in_traffic)
             }}
            onError={(errorMessage) => {
                //console.log(errorMessage);
              }}
        />

    setDistance(distance,duration_in_traffic){
        this.setState({distance:parseFloat(distance),durationInTraffic:parseInt(duration_in_traffic)});
    }

**Comment by bramus** [comment]
You have a binding: `setDistance` is not bound to your class instance, so `this.setState()` won't work there (as it there is no `this` in it).

Use [one of these 5 suggested approaches](https://www.bram.us/2016/08/18/react-binding-patterns-5-approaches-for-handling-this/) to solve it. My preference goes out to number 5 _“Arrow Function in Class Property“_:

```js
class Example extends React.Component {

  // By using an Arrow Function, the function will be bound to the execution context from which it is called (“lexical this”)
  setDistance = (distance,duration_in_traffic) => {
    this.setState({distance:parseFloat(distance),durationInTraffic:parseInt(duration_in_traffic)});
  }

  render() { 
    // ...
  }
}
```

See [Javascript ES6 — Arrow Functions and Lexical `this`](https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4) for more info.

**Comment by 14076156deiefyp** [comment]
I have tried and it should not be related to this issue since it can successfully execute the code inside setDistance, but somehow it will drive onReady to **infinity loop** when I call the function or this.setState().

**Comment by bramus** [comment]
Ok, think I see it now: setState() will trigger a re-render, thus re-rendering `MapViewDirections`. Normally a re-render with the same data won't happen, but I'll look further into it to be sure …

**Comment by sidious18** [comment]
The problem is in this line:

if ((nextProps.origin != this.props.origin) || (nextProps.destination != this.props.destination) || !isEqual(nextProps.waypoints, this.props.waypoints)) {

You should not compare arrays in JS directly, because two arrays are always not equal. You should compare route values. Use isEqual instead of !== to fix this issue.

**Comment by bramus** [comment]
Good point @sidious18. Working and testing a fix right now.

**Comment by bramus** [comment]
It took a bit longer than expected, but couldn't trigger this one myself at first. The “culprit” was the fact that I used an array holding all coordinates in my state. This then resulted in the fact that the references remained the same all the time, even after a re-render.

In contrast: the example above creates a new object on every render. Even though `react-native-maps-directions` can now catch this, I'd advise against this use.

Thanks to all involved for their input :)
