### ISSUE TITLE
TypeError: undefined is not an object (evalutating 'waypoints.map')

### ISSUE THREAD

**Issue by chamodKanishka** [bramus/react-native-maps-directions#131]
this error was occure when i add this module inside of my mapview. previously also use this module and that time only error was waypoints not shows correctly. but now this error was generated when i add waypoints or without adding waypoints

**Comment by kalleriakronos24** [comment]
^Same Error here

**Comment by kalleriakronos24** [comment]
the way to fix the error 'waypoints.map' of undefined is adding "waypoints" props into the <MapViewDirections>, but if adding the values (origin and destination array of object) of the waypoints props , it still doesnt work.

**Comment by chamodKanishka** [comment]
> 
> 
> the way to fix the error 'waypoints.map' of undefined is adding "waypoints" props into the , but if adding the values (origin and destination array of object) of the waypoints props , it still doesnt work.

are you solved this?

**Comment by kalleriakronos24** [comment]
![waypoints_error](https://user-images.githubusercontent.com/46893395/76705260-b19e3400-6719-11ea-8029-2b519b694736.png)

 > literally, not solved
https://pastebin.com/Y7WTtQZh

**Comment by bramus** [comment]
Which version of `react-native-maps-directions` are you using? Could be a bug in an older version. In #130 it is suggested to upgrade to the latest version.

_(Please report the current version before upgrading, so that I can take not of the issue with that version, thanks!)_

**Comment by chamodKanishka** [comment]
previously I'm work with 1.7.3 and its show road with region and destination when added(but way points didn't work). also shows the mark of the road. but after 1.7.4 this error was occurred.but after im try with prevous version. but now same problem occure

**Comment by shirokun20** [comment]
Downgrade to 1.7.0

**Comment by shirokun20** [comment]
<img width="1680" alt="Screen Shot 2020-03-17 at 10 59 41" src="https://user-images.githubusercontent.com/15245975/76820700-76e1ec00-683e-11ea-856f-2f515d26321f.png">

**Comment by chamodKanishka** [comment]
is it works with waypoints?. what is the google maps version. i think this error was combination of react native maps and this.(versions error)

**Comment by shirokun20** [comment]
I agree with you @chamodKanishka.

my version google maps and directions

    "react-native-maps": "0.26.1"
    "react-native-maps-directions": "^1.7.0"

but work fine

**Comment by chamodKanishka** [comment]
react-native-maps updated 0.27 three days ago. it might be a case for this.

**Comment by bramus** [comment]
Version 1.7.5 with a fix for this got released. Thanks for the input, everyone!

**Comment by chamodKanishka** [comment]
this error still occure

**Comment by chamodKanishka** [comment]
thanks for your contribution. everything working great now
