### ISSUE TITLE
Works, but map is gray

### ISSUE THREAD

**Issue by oscarsales** [bramus/react-native-maps-directions#136]
I am using a map, and the "OnReady" callback is working, it returns the data with the distance, duration, coordinates, etc. "OnError" is not triggered, so no errors. My billing is active, in fact it's the same api key I use for Google places, and it works.
So I get the data correctly, but the map looks all gray, like this:
![screenshot](https://user-images.githubusercontent.com/42787403/78131690-c407b580-741b-11ea-9a47-faf72eb208d7.jpeg)

I made my own component to contain the map:

```
render() {
        const { origin, destiny, waypoints, onReady, height} = this.props;

        let h = height ? height : 300;

        return <MapView
        style={{width: '100%', height: h}}>
            <MapViewDirections
            origin={origin}
            destination={destiny}
            waypoints={waypoints}
            apikey={config.mapsApiKey}
            language={translate.deviceLanguage()}
            onReady={(data) => {
                if (onReady) onReady(data);
            }}
            onError={(err)=>{
                utils.log("Map error", {error: err});
            }}/>
        </MapView>
    }
```

**Comment by frost4869** [comment]
maybe you missed this step ?
" if you're using an existing Google Maps API Key make sure you've enabled the Google Maps Directions API for that key"

**Comment by oscarsales** [comment]
> maybe you missed this step ?
> " if you're using an existing Google Maps API Key make sure you've enabled the Google Maps Directions API for that key"

Yes, that was my mistake. I had the API key enabled for google maps and google places, but I missed that. What confused me is that react-native-maps-directions returned me data like coordinates and distance, so I thought it worked, but the map was just gray. I guess I obtained that data because my API key was enabled for other google maps services, but not for the map. Anyway, it's solved now.
