### ISSUE TITLE
How should I restrict my api key?

### ISSUE THREAD

**Issue by ShunyaWatanabe** [bramus/react-native-maps-directions#154]
https://developers.google.com/maps/api-key-best-practices

^I've spent some time reading this, and realized it recommends us to use a proxy server to call the directions API. Even with Application restriction, the recommended(?) way of restricting it is "HTTP referer restriction", not Android or iOS apps. What is the referer in our case? Also, I've tried restricting the api key with application restriction as "Android apps" and added the app signing certificate (SHA1) and package name, but I got an error saying "Error on GMAPS route request ... not authorized to use this API key ...".

Could you explain how restriction of the api key works in your package and/or add the explanation in README?

**Comment by miroslavskela** [comment]
Same problem here. I have api key restricted to android apps, and enabled maps and directions api, and maps are working but directions not with "**ReactNativeJS: MapViewDirections Error: Error on GMAPS route request: This IP, site or mobile application is not authorized to use this API key. Request received from IP address xx.xxx.xxx.xxx, with empty referer**" error. I tried with key that does not have restrictions and it works. SO if someone knows how to get it work but with restrictions it would be great. Thank you.

**Comment by bramus** [comment]
The refererer [sic] is only used when making XHR requests on websites. Its value is set to the website that makes the request.

For API Keys for use with `react-native-maps-directions` best is to:

1. Limit the API key to iOS or Android Applications only
2. Limit the API key to use the Directions API only

In the screenshot below you can find an example where I only applied 2, as I use my key for local testing in both iOS and Android apps.

<img width="900" alt="Screenshot 2021-09-28 at 23 23 55" src="https://user-images.githubusercontent.com/213073/135167985-ca2ac630-46e2-4d50-99c3-b11bc99945d3.png">

If you're having issues, start out with no restrictions, and then add them one by one to see where it breaks.

**Comment by kuzkokov** [comment]
hey @bramus, I don't think that's a solution.
limiting API keys for android or iOS is working only for native SDKs. your library is not using them, but making regular HTTP requests, so such restrictions would not let this library work at all

**Comment by farazahmed12** [comment]
Same here
