### ISSUE TITLE
How to rotate map when user position changes with live directions ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [bramus/react-native-maps-directions#162]
Hi every body 

I'm working on react-native maps with the current repo package 

I have a button 'Get directions', once clicked the directions and route will be displayed and the navigation starts

My Question is : 

How to rotate map according to directions when user moves ?

Same as current Google Maps live directions

**Comment by bramus** [comment]
This is a `react-native-maps` issue/question, not a `react-native-maps-directions` one.

**Comment by MustaphaGhlissi** [comment]
Thanks, 

But I saw the other plugin used in your example that' why I just mentioned it to get help if someone had the same issue .
