### ISSUE TITLE
[Q&A] Is it possible to switch to use another api call?

### ISSUE THREAD

**Issue by kristoff2016** [bramus/react-native-maps-directions#164]
Hello, 

First, thank you so much for a great plugin for us. 

Is it possible to change `directionsServiceBaseUrl` 

https://api.openrouteservice.org/v2/directions/ instead of google map direction API? 

thank you

**Comment by kristoff2016** [comment]
As you mention here => 

`Once the directions in between destination and origin has been fetched, a MapView.Polyline between the two will be drawn. Whenever one of both changes, new directions will be fetched and rendered.`

this will count as request per changed (`new directions will be fetched and rendered`)? 

can we reduce it? 

Thank you

**Comment by bramus** [comment]
> Is it possible to change `directionsServiceBaseUrl`
Yes, that's exactly what the prop allows you to do.

> this will count as request per changed. can we reduce it?
You can always cache params and results on the client side to reduce the number of requests.

**Comment by kristoff2016** [comment]
Thank you for your perfect answer
