### ISSUE TITLE
[Question] Does this lib possible to do like google map?

### ISSUE THREAD

**Issue by kristoff2016** [bramus/react-native-maps-directions#165]
Hi again, 

Does this lib allow to like google map that user can have button start then it will show direction?

Please check the image below 

![2021-01-26 10 16 39](https://user-images.githubusercontent.com/16773770/105795545-9bab0200-5fbf-11eb-8150-9599f86e45ed.jpg)

Thank you

**Comment by bramus** [comment]
This library provides a wrapper around the Google Maps Directions API, and will render a `MapView.Polyline`. You'll have to implement all other visual things yourself. Be sure to also check out https://github.com/flyandi/react-native-maps-navigation, which might be a better fit for your use case.

**Comment by kristoff2016** [comment]
Thank you for always provide good solution
