### ISSUE TITLE
Directions not rendered on iOS if provider is PROVIDER_GOOGLE

### ISSUE THREAD

**Issue by dayaki** [bramus/react-native-maps-directions#167]
If you use `provider={PROVIDER_GOOGLE}` for MapView, the directions won't render but will render perfectly if the `props` is not used.

Any help/pointer please. I need to use GoogleMaps on iOS

**Comment by zoolle** [comment]
I think you are talking about `react-native-maps`

Have you added `AirGoogleMaps` in you workspace? `/node_modules/react-native-maps/lib/ios/`and you will find `AirGoogleMaps`. Drag it in your project workspace's project folder. Your structure will be like this

```
YourProject
 - AirGoogleMaps
 - YourProject
 - Libraries
 - Products
 - Frameworks
 - Pods
-Pods
```

**Comment by dayaki** [comment]
I have been able to get GoogleMaps to work on iOS, which means AirGoogleMaps is in my workspace. If I remove `provider={PROVIDER_GOOGLE}`, the directions shows.

Do you mean this is not from this package but `react-native-maps`?

**Comment by bramus** [comment]
MapView indeed is not from this package, but from `react-native-maps`
