### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by janvdt** [bramus/react-native-maps-directions#17]
I have a problem the map shows but i get a warning in my IOS simulator that the Network Request failed? When i inspect in the remote debugger the api of google directions gets called and there is a response. Any idea what could be wrong?

**Comment by bramus** [comment]
The Directions API wil always send a successful response (HTTP 200) back, even in case of a faulty query. The contents of said response will then indicate that it's erroneous.

Between which 2 locations are you routing?

**Comment by janvdt** [comment]
Ok the problem from Network request is resolved. It was a CORS issue because remote JS debug was enabled. My bad

I Have na new problem 

`--------- beginning of crash
02-16 12:07:46.385 10186-10186/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.Paxi, PID: 10186
                                                   com.facebook.react.bridge.UnexpectedNativeTypeException: Tried to read an int, but got a non-integral double: 20.571429`

Any idea on this this is when running on android physical device

**Comment by bramus** [comment]
Hi @janvdt, I'll close this issue as the original thing you mentioned has been fixed. Feel free to open a new issue for the new issue you're having.
