### ISSUE TITLE
Get duration of the remaining trip

### ISSUE THREAD

**Issue by musabgulfam** [bramus/react-native-maps-directions#181]
How do I get the duration of the trip, one way is to get it from the `onReady` prop. But is there anyway to get the duration afterwards, because `onReady` callback is only executed once the direction is in 'ready' status.

**Comment by zoolle** [comment]
@musabgulfam if you change any of the `origin` or `destination` values it will re-render so `onReady` will fire again you might also use `resentOnChange: true`

**Comment by musabgulfam** [comment]
Thank you very much @zoolle, the issue is resolved.
