### ISSUE TITLE
How to start navigation(car) for the found directions by <MapViewDirections>?

### ISSUE THREAD

**Issue by burakkbilginn** [bramus/react-native-maps-directions#186]
There is a mapview, and mapviewdirections inside it. Everything is done well, and origin and destination coordinates are acquired briefly as below:

```
<MapView >
   <MapViewDirections />
</MapView>
```

Now, how can I start the navigation by car i.e by clicking a button? Is there a built in feature for that? 
Or should I build everything step by step for mocking up the native google maps app?

**Comment by EmmanuelSkapple** [comment]
Can u resolve this?


> There is a mapview, and mapviewdirections inside it. Everything is done well, and origin and destination coordinates are acquired briefly as below:
> 
> ```
> <MapView >
>    <MapViewDirections />
> </MapView>
> ```
> 
> Now, how can I start the navigation by car i.e by clicking a button? Is there a built in feature for that? Or should I build everything step by step for mocking up the native google maps app?

can u resolve this?

**Comment by bramus** [comment]
That's something that's not part of the scope of `react-native-maps-directions`
