### ISSUE TITLE
Feature Request : MapView Zoom Level

### ISSUE THREAD

**Issue by GeekRishabh** [bramus/react-native-maps-directions#2]
Can you add fItToSuppliedMarkers support in this package so that the mapview can have the Source/origin & the destination visible in the same mobile view . where the markers can be pointing to origin & destination address/location ?

**Comment by bramus** [comment]
Hi @GeekRishabh,

With the addition of the `onReady` event/callback in the 1.1.0 release this is now possible:

```js
class Example extends Component {

  mapView = null;

  render() {
    return (
      <MapView
        initialRegion={…}
        ref={c => this.mapView = c}
      >
        <MapViewDirections
          origin={origin}
          destination={destination}
          onReady={(result) => {
            this.mapView.fitToCoordinates(result.coordinates, {});
          }}
        />
      </MapView>
    );
  }
}
```

The key part is that you keep a reference to the `MapView` component. Using the `onReady` event you can pass the route's `coordinates` into the `mapView`'s `fitToCoordinates` method.
