### ISSUE TITLE
Check render method for 'MapViewDirections'

### ISSUE THREAD

**Issue by Judefabi** [bramus/react-native-maps-directions#200]
//someone please edit this so that the directions will be shown. when I comment out the mapviewdirections part it works perfectly, for some reason I'm getting apViewDirections Error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MapViewDirections`.

Can't seem to solve it and I'm new to mapviewdirections

import {StyleSheet, Text, View, Dimensions} from 'react-native';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';
import React from 'react';
import MapViewDirections from 'react-native-maps-directions';

const origin = {latitude: 37.3318456, longitude: -122.0296002};
const destination = {latitude: 37.771707, longitude: -122.4053769};
const GOOGLE_MAPS_APIKEY = '....';

const App = () => {
  return (
    <View style={styles.container}>
      <MapView
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        region={{
          latitude: 0.613145261539282,
          longitude: 34.76457110440688,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}>
        <MapViewDirections
          origin={origin}
          destination={destination}
          apikey={GOOGLE_MAPS_APIKEY}
        />
      </MapView>
    </View>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});

**Comment by Judefabi** [comment]
solved it by navigating to mapviewdirections.js and editing the code there using this

diff --git a/node_modules/react-native-maps-directions/src/MapViewDirections.js b/node_modules/react-native-maps-directions/src/MapViewDirections.js
index ac08d73..f04ef10 100644
--- a/node_modules/react-native-maps-directions/src/MapViewDirections.js
+++ b/node_modules/react-native-maps-directions/src/MapViewDirections.js
@@ -1,6 +1,6 @@
 import React, { Component } from 'react';
 import PropTypes from 'prop-types';
-import MapView from 'react-native-maps';
+import { Polyline } from 'react-native-maps';
 import isEqual from 'lodash.isequal';
 
 const WAYPOINT_LIMIT = 10;
@@ -305,7 +305,7 @@ class MapViewDirections extends Component {
 		} = this.props;
 
 		return (
-			<MapView.Polyline coordinates={coordinates} {...props} />
+			<Polyline coordinates={coordinates} {...props} />
 		);
 	}

**Comment by bramus** [comment]
Fix is included in version 1.9.0

**Comment by Judefabi** [comment]
Glad to hear that let me update mine
Thanks for the good work @bramus
