### ISSUE TITLE
App crashes when GPS is not enabled

### ISSUE THREAD

**Issue by DFRZ7** [bramus/react-native-maps-directions#208]
Hi Team, we are testing our application without the use of GPS. We noticed that at the time we move to a view in which we have loaded the <MapViewDirections /> component, the app crashes, no warning or error given. 

We did notice that the app is able to keep running if we simply comment out the <MapViewDirections /> section, and just leave <MapView /> with markers. Attempted as well commenting out all additional options we had enabled for the directions component, but no luck.

The environment details:

Expo SDK 47
React Native 0.70.5

Being this said, we were wondering if there could be something wrong that we are doing, or simply the functionality is not currently supported.

Thank you for the time, and if you need any additional details, just let us know.

**Comment by bramus** [comment]
This project does not rely on GPS, as it routes between two locations. Where those locations come from (fixed data, GPS, etc.) falls outside of the scope of this project.
