### ISSUE TITLE
Dynamic rerendering

### ISSUE THREAD

**Issue by sidious18** [bramus/react-native-maps-directions#21]
Hi @bramus ! We use a fork of this module to build dynamic routes, depending on user's position. And now, if user changes it, the code resets current state and waits for google's response to get new coordinates. But is it necessary to reset the state? This logic causes blinking of a polyline (because there is a small time interval between the reset of the state and displaying a new polyline).
Anyway, thanks for the great work you have done!

**Comment by bramus** [comment]
Hi, I added this into the 1.5.0 release :)
