### ISSUE TITLE
'Yarn' is not recognized.

### ISSUE THREAD

**Issue by 8Ozymandias** [bramus/react-native-maps-directions#23]
I utilized the command provided in the instruction: _yarn add react-native-maps-directions_ in the Node.js command prompt. 

However, it gives the result: 'yarn' is not recognized as an internal or external command, operable program or batch file.

Please Help

I am new to all of this programming stuff.

**Comment by bramus** [comment]
Please make sure dev environment is set up properly. As the error indicates you don't have yarn installed.

**Comment by ggdegreat** [comment]
@bramus your installation guide is too simple, i suggest adding more support like npm installation because not all people are using yarn.

**Comment by bramus** [comment]
Installation instructions using Node's `npm install` command added: https://github.com/bramus/react-native-maps-directions/commit/337df45c5a38b14ab038dfaf3bc3f36fa80358c4

Installation instructions on Node/Yarn/React Native Maps/React Native/Xcode/Android Studio/Homebrew/…/macOS fall outside of the scope of the instructions for `react-native-maps-directions` itself.
