### ISSUE TITLE
How to integrate/make use of the code

### ISSUE THREAD

**Issue by 8Ozymandias** [bramus/react-native-maps-directions#24]
I am having trouble understanding how to make use of the react-native-maps-direction code here and or other react-native code/code samples.

I followed the steps on the [React Native website (Getting Started)](http://facebook.github.io/react-native/docs/getting-started.html). 

It resulted as it said it would, a project/module named _AwesomeProject_. Within that, is a file named App.js which was generated with the whole set up/configuration process and not by me.

**NOW**...

Is it that I just copy and paste the contents of react-native-maps-direction code sample into AwesomeProject? or is it that I open the contents of the react-native-maps-direction code sample with the Atom Editor?  or is there some other step?

**Comment by bramus** [comment]
Hi Shayn, before getting started with `react-native-maps` I'd recommend you to first get comfortable with React Native itself first.

There are plenty of external tutorials for this, and even the The React Native documentation itself has you covered with their page [Learn The Basics](http://facebook.github.io/react-native/docs/tutorial.html).
