### ISSUE TITLE
Getting not authorized access when using this module

### ISSUE THREAD

**Issue by djalmaaraujo** [bramus/react-native-maps-directions#26]
I am using the react-native-maps and it's already working, but when I try to use the same key using this module, I am getting this message:

![image](https://user-images.githubusercontent.com/3402/37306454-b12259a2-262f-11e8-83f9-e8f501eb4dbf.png)

```js
<MapViewDirections
          origin={origin}
          destination={destination}
          apikey={GOOGLE_MAPS_APIKEY}
        />
```

**Comment by bramus** [comment]
You must enable the Directions API for your API key. You can do this on https://console.developers.google.com/ (Select your API key from the dropdown at the top, then click on "Enable APIs and Services", …)

**Comment by djalmaaraujo** [comment]
I needed to add Maps directions api to the API permissions.

**Comment by djalmaaraujo** [comment]
Thank @bramus just saw your comment.
