### ISSUE TITLE
How to make the view always visible with the 2 points?

### ISSUE THREAD

**Issue by djalmaaraujo** [bramus/react-native-maps-directions#27]
Example. I am rendering 2 points.. but I want the zoom to always show the 2 points. So I need to adjust. I am not sure what calc is that or if it's too complicate.

This is the map:

![image](https://user-images.githubusercontent.com/3402/37307996-8b52e80e-2634-11e8-8052-95f8fb5d132b.png)

What would be the calc to always show the 2 points? :}

**Comment by bramus** [comment]
Yes, you can use the `onReady` callback for this, in combination with [the `fitToCoordinates` method of the `<MapView />` component](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods):

```
      <MapView
        initialRegion={…}
        ref={c => this.mapView = c}
      >
          <MapViewDirections
            origin={…}
            destination={…}
            apikey={GOOGLE_MAPS_APIKEY}
            onReady={(result) => {
              this.mapView.fitToCoordinates(result.coordinates, {
                edgePadding: {
                  right: (width / 20),
                  bottom: (height / 20),
                  left: (width / 20),
                  top: (height / 20),
                }
              });
            }}
          />
      </MapView>
```

Note that a reference to the `<MapView />` component was made (`this.mapView`) in order to make things work.

**Comment by djalmaaraujo** [comment]
Thanks @bramus, you are super fast.

**Comment by shahrajk** [comment]
can you share an example. @djalmaaraujo @bramus

**Comment by thorizer** [comment]
@bramus how to use this in a functional component?    ( this.mapView instance )
