### ISSUE TITLE
how to get EAT (estimated arrival time)

### ISSUE THREAD

**Issue by starba3** [bramus/react-native-maps-directions#32]
iam trying to build navigation app which shows the nearest vehicle and it's expected arrival time.
does the package provide such function, and if not is there any other way?

**Comment by malithjkmt** [comment]
onReady returns estimated duration in hours.

**Comment by moveo** [comment]
@malithjkmt Duration unit is coming in minute or hour? Because right now we are getting in minute

**Comment by bramus** [comment]
@moveo divide it by 60 and you have it in hours ;-)
