### ISSUE TITLE
Animate drawing of the polyline

### ISSUE THREAD

**Issue by shokimble** [bramus/react-native-maps-directions#34]
Hi,

How could you animate the drawing of the polyline when the directions are returned? I would like to make it look like someone's almost drawing the directions with a pen.

Apart from that....thanks very much for this. It saved me a couple of hours doing it myself.

**Comment by bramus** [comment]
Great idea! 

Unfortunately I won't be able to help you out with this one: the [`Polyline`](https://github.com/react-community/react-native-maps/blob/master/docs/polyline.md) Component, whose data is generated by `react-native-maps-directions`, is part of the [`react-native-maps`](https://github.com/react-community/react-native-maps/).

Therefore an animation feature will need to be requested over at the [`react-native-maps`](https://github.com/react-community/react-native-maps/) project.

Regards,
Bramus.
