### ISSUE TITLE
Show public transport names as waypoints in transit mode

### ISSUE THREAD

**Issue by EzeInverni** [bramus/react-native-maps-directions#35]
In "transit mode" the line is rendered correctly following the intersection of different public transports, but there is no way to distinguish them from each other, there is only one flat line. Does anyone know how to achieve this with waypoints or something, like in google maps website? Thanks!

![captura de pantalla 2018-04-20 a la s 00 39 37](https://user-images.githubusercontent.com/16846926/39029666-65b6bdf6-4433-11e8-8f0b-38ab0ab784ea.png)

**Comment by bramus** [comment]
Do you mean you want to color a few segments differently? Or do you want to add those extra little callouts on the map?

**Comment by EzeInverni** [comment]
Coloring or changing to a dotted line for the walking segments would help a little, but the main problem I think it is not knowing the name of the bus or metro line.  Waypoints should work but I don't know how to get the array with the coordinates of stops and names of transports provided by Google.

**Comment by EzeInverni** [comment]
I just read in the documentation that waypoints are not allowed in transit mode, so that is not the way around. But there must be a way to get that info at least and render some markers. Having only the route without the stop markers makes transit mode not very useful.

**Comment by bramus** [comment]
Closing this as it's more related to the Google Maps Directions API itself.
