### ISSUE TITLE
Distance andd Duration Positioning

### ISSUE THREAD

**Issue by SirPhemmiey** [bramus/react-native-maps-directions#38]
Hi @bramus , Having known the KM and minutes between two coords, is there anyway i can put that beside the line or somewhere visible to them?

**Comment by bramus** [comment]
Hi, this is not directly part of the scope of `react-native-maps-directions`, but what you could do is  add [a custom `Marker`](https://github.com/react-community/react-native-maps#rendering-a-marker-with-a-custom-view) – with said text/label inside it – on a coordinate that's part of the trajectory.
