### ISSUE TITLE
Flights transportation mode not supported

### ISSUE THREAD

**Issue by AyoubAbdellaoui** [bramus/react-native-maps-directions#40]
This API support the use of the DirectionsService object to fetch directions for different travel modes. BUT, it doesn't support the **flights travel mode**. 
 So is their any way to do this.
THNX in advance.

**Comment by bramus** [comment]
The supported Travel Modes are [the Travel Modes supported by the Google Maps Directions API](https://developers.google.com/maps/documentation/javascript/directions#TravelModes). These are:

- `DRIVING` (Default) indicates standard driving directions using the road network.
- `BICYCLING` requests bicycling directions via bicycle paths & preferred streets.
- `TRANSIT` requests directions via public transit routes.
- `WALKING` requests walking directions via pedestrian paths & sidewalks.

Flights are therefor not supported.
