### ISSUE TITLE
 MapViewDirections Error: This API project is not authorized to use this API.

### ISSUE THREAD

**Issue by Manoj002** [bramus/react-native-maps-directions#41]
Hello,

Im trying to use the places api with react-native-maps-direction but got this error.

Is there anything that can be done about this...???

Any help will be appreciated

**Comment by bramus** [comment]
You're getting this error from the Google Maps Directions API. Please properly configure your API Key.

See [the description of the `apikey` prop in the `README`](https://github.com/bramus/react-native-maps-directions#props) for more details.

**Comment by Manoj002** [comment]
is it like it works only with directions api and not with places api..???

**Comment by wandieinnocents** [comment]
Sometimes google needs billing enabled so that you are able to have full access , check your billing account too.
