### ISSUE TITLE
Tag showing distance

### ISSUE THREAD

**Issue by Manoj002** [bramus/react-native-maps-directions#43]
I am displaying a route using react-native-maps-direction between two locations in react-native-maps.

How can i show distance, after user clicks on polyline
Im done with calculations and im getting the distance in meters, im asking that if user clicks on polyline how do i show this distance to user...

Any code i am missing out???

**Comment by bramus** [comment]
The distance of the route is returned in [the `onReady` callback](https://github.com/bramus/react-native-maps-directions#eventscallbacks).

You can expose this value by – for example – storing in the state and rendering it inside a `Text` component.
