### ISSUE TITLE
different route colors

### ISSUE THREAD

**Issue by Esniper90** [bramus/react-native-maps-directions#50]
How can i set different colors for each path? for example a to b (red). b to c (blue)...

`<MapView
	initialRegion={{
	  latitude: LATITUDE,
	  longitude: LONGITUDE,
	  latitudeDelta: LATITUDE_DELTA,
	  longitudeDelta: LONGITUDE_DELTA
	}}
	style={StyleSheet.absoluteFill}
	ref={c => (this.mapView = c)}
	onPress={this.onMapPress}
	>
	{this.state.coordinates.map((coordinate, index) => (
	  <MapView.Marker key={`coordinate_${index}`} coordinate={coordinate} pinColor={this.state.colors[index]} />
	))}
	{this.state.coordinates.length >= 2 && (
	  <MapViewDirections
		origin={this.state.coordinates[0]}
		waypoints={
		  this.state.coordinates.length > 2
			? this.state.coordinates.slice(1, -1)
			: null
		}
		destination={
		  this.state.coordinates[this.state.coordinates.length - 1]
		}
		apikey={GOOGLE_MAPS_APIKEY}
		strokeWidth={3}
		strokeColor= {this.state.colors[this.state.coordinates.length - 1]}
		onReady={result => {
		  this.mapView.fitToCoordinates(result.coordinates, {
			edgePadding: {
			  right: width / 20,
			  bottom: height / 20,
			  left: width / 20,
			  top: height / 20
			}
		  });
		}}
	  />
	)}
</MapView>`

this code colorizes the whole path from a to c

**Comment by alisherakb** [comment]
Any suggestion?

**Comment by bramus** [comment]
Until this is properly supported, you can always work around this
limitation by including two (or more) routing components, each with their
own color. Do note that your number of requests to the Google Maps
Directions API will also increase.
