### ISSUE TITLE
showsTraffic causes  iOS app crashing 

### ISSUE THREAD

**Issue by hashmatmuqbil** [bramus/react-native-maps-directions#51]
Hi,

I'm using the props showsTraffic and mapLayer on MapView but when I toggle between 'standard' and 'satellite' and then click on the button with showsTraffic prop the app crashes on iOS but it works fine on Android

**Comment by bramus** [comment]
This is a `react-native-maps` related issue, and not a `react-native-maps-directions` one.

Please file an issue [over there](https://github.com/react-community/react-native-maps).
