### ISSUE TITLE
Origin and destination different pin colors

### ISSUE THREAD

**Issue by e-ndrus** [bramus/react-native-maps-directions#52]
Is there a way to make origin and destination marker pins have different colors/icons? Would greatly appreciate a hint how to do that. Thanks in advance!

**Comment by Norris1z** [comment]
Yes!. 
`<MapView.Marker coordinate={...} pinColor='#000000'/>` For the origin
`<MapView.Marker coordinate={...} pinColor='#ffffff'/>` For the Destination

You can change the color of the marker using the `pinColor` prop.
Check [the marker documentation](https://github.com/react-community/react-native-maps/blob/master/docs/marker.md)

**Comment by bramus** [comment]
As @Norris1z wrote, you need to add `MapView.Marker` components, positioned at the origin and destination.
