### ISSUE TITLE
Warning: Failed prop type: Invalid prop `destination` supplied to `MapViewDirections`

### ISSUE THREAD

**Issue by jpdesignerrio** [bramus/react-native-maps-directions#54]
```
<MapView
  region={{
	latitude: this.state.location.latitude,
	longitude: this.state.location.longitude,
	latitudeDelta: LATITUDE_DELTA,
	longitudeDelta: LONGITUDE_DELTA,
  }}
  onRegionChange={this.onRegionChange}
  initialRegion={{
	latitude: this.state.location.latitude,
	longitude: this.state.location.longitude,
	latitudeDelta: LATITUDE_DELTA,
	longitudeDelta: LONGITUDE_DELTA,
  }}
  onMapReady={Platform.OS === 'android' ? this.onMapLayout : null}
  onLayout={Platform.OS === 'ios' ? this.onMapLayout : null}
  mapType='standard'
  showsCompass
  showsBuildings>
  { this.state.isMapReady &&
	<MapViewDirections
	  origin={this.state.location}
	  destination={this.state.destination}
	  apikey={this.state.maps_apikey}
	  strokeWidth={3}
	  strokeColor="blue"
	/>
  }

</MapView>
```

this returns:
Warning: Failed prop type: invalid prop `destination` supplied to `MapViewDirections`.

This is a bug? Any solution?

**Comment by Norris1z** [comment]
Is `this.state.destination` a `LatLng` pair? I had a same error when i passed an `AnimatedRegion` instead of `{latitude:...,longitude:...}` to the `destination` prop.

**Comment by jpdesignerrio** [comment]
A get the Latitude and Longitude asyncronous, and set them to state like this:
```
let latLongObj = {
      latitude: response.address.latitude,
      longitude: response.address.longitude
    };

this.setState({
      destination: latLongObj
    });
```

**Comment by jpdesignerrio** [comment]
Besides that, apikey is returning "You have exceeded your daily request quote for this API", but I did less than 3 requests. After accessing the Google API account, I could see that the request limit was not exceeded.

**Comment by jpdesignerrio** [comment]
I found the problem! Just parse the 

> response.address.latitude

 and 

> response.address.longitude

 to float, it's string!
(Using parseFloat function)

**Comment by Puwaga** [comment]
Change the destination to an int if it is a string ,that sometime causes the the problem

**Comment by moustaouiSalaheddine** [comment]
cast value every change
{ latitude: parseFloat(latitude), longitude: parseFloat(longitude) }
