### ISSUE TITLE
Navigation with dots not just a stroke

### ISSUE THREAD

**Issue by veselinnguyen** [bramus/react-native-maps-directions#55]
Hi @bramus,

I was checking the code, and I noticed that the only option for drawing the rote between two coordinates is a whole stroke, but not Dots or any other type. I saw that the MapViewDirections properties are bind with interface MapPolylineProps which supports only:
```
         strokeWidth?: number;
         strokeColor?: string;
```

```
         <MapViewDirections
                             strokeWidth={5}
                             strokeColor="orange"
         ...
```

Can this be extended to support more than one type of path (stroke): ?
```
         navigationPathType?: stroke | dots | whatever
         navigationPathWidth?:  number
         navigationPathColor?:  string
```

Regards,

V. Nguyen

**Comment by bramus** [comment]
The routes are being rendered by a `MapView.Polyline`, so all [its props](https://github.com/react-community/react-native-maps/blob/master/docs/polyline.md#props) are accepted.
