### ISSUE TITLE
MapViewDirections - You have exceeded your daily request quota

### ISSUE THREAD

**Issue by shreekant123** [bramus/react-native-maps-directions#59]
I am trying to run MapViewDirections code. but it showing error that- "You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account"

**Comment by bramus** [comment]
This is a Google Directions API related error. With a free account you only get a limited set of requests per day/month. Switch to a paid account to get more request (which will be billed)

**Comment by shreekant123** [comment]
Okay...

**Comment by ArthurKnoep** [comment]
What is the limit for a free account. Because it's not mark on the offcial documentation
