### ISSUE TITLE
Does this work with indoor maps?

### ISSUE THREAD

**Issue by resting** [bramus/react-native-maps-directions#63]
I'm plotting a route between 2 points in a mall.
The route generated is different from the one on maps.google.com.
Specifically, it goes outside of the mall and along the roads.

Has anyone tried to plot a route indoors?

**Comment by bramus** [comment]
As far as I can tell, [from a note in the docs](https://developers.google.com/maps/documentation/directions/intro#optional-parameters): ”Only requests that include an API key or a Google Maps APIs Premium Plan client ID will receive indoor steps by default.”.

Over at GIS Stack Exchange [the question has been asked before](https://gis.stackexchange.com/questions/150808/how-to-get-indoor-directions-by-using-google-api), but still without any answer.

**Comment by bramus** [comment]
Sidenote: Leaving this issue open for now _(perhaps someone knows the answer?)_, but am considering to mark it as `invalid` – as it's a Google Maps Directions API issue – in the future.

**Comment by resting** [comment]
I managed to get it to plot indoors. Could be related to the lat/lng I provided.
Was able to plot indoors after I used "names" for the `origin` and `destination` instead of lat/lng object.

**Comment by bramus** [comment]
Thanks for providing the info! 👍
