### ISSUE TITLE
Critical bug: bicycling => BICYCLING

### ISSUE THREAD

**Issue by n-lavrenko** [bramus/react-native-maps-directions#66]
`bicycling` not working, but `BICYCLING` - yes. 
Critical bug, please, fix it. 
P.S. Also in Google documentation all keys in uppercase:
![image](https://user-images.githubusercontent.com/7901225/50085837-3abf7600-020c-11e9-82f1-bd6e96c9977e.png)

**Comment by bramus** [comment]
Feel free to open up a PR to add this. I'll gladly merge.

**Comment by bramus** [comment]
Closed in #68
