### ISSUE TITLE
param origin with wrong name in read-me.

### ISSUE THREAD

**Issue by luanfelipecosta** [bramus/react-native-maps-directions#69]
I noticed that your  _getDirections_ function is expecting a **source** param, not **origin**

`getDirections ({ destination, source , params = [] } = {}) {
   ...
  }
`

**Comment by bramus** [comment]
Can't seem to find (anymore) what you're talking about so closing it.

Feel free to add a comment to clarify what exactly is wrong, and I'll gladly reopen.
