### ISSUE TITLE
Recalculate direction

### ISSUE THREAD

**Issue by mdelclaro** [bramus/react-native-maps-directions#73]
I'd like to know if there is a away to recalculate the polylines while the user moves.

The only way I could think of is every time the user's position changes, ask for a new origin/destination direction. But wouldn't it require a lot from the Google API? This way I might get that limit quota by only testing my app.

Thanks.

**Comment by hesan-aminiloo** [comment]
Same issue here

**Comment by arshidkv12** [comment]
Same issue here also.

**Comment by arshidkv12** [comment]
Small solution https://github.com/arshidkv12/react-native-live-delivary

**Comment by vrinch** [comment]
Same issue here

**Comment by bramus** [comment]
Please check the README:

> Once the directions in between `destination` and `origin` has been fetched, a `MapView.Polyline` between the two will be drawn. **Whenever one of both changes, new directions will be fetched and rendered.**

_(emphasis mine)_

**Comment by arshidkv12** [comment]
Destination and origin is same. My doubt is, it will calculate new direction if user is going to new route.
