### ISSUE TITLE
Testers needed: version 1.7.0.beta-*

### ISSUE THREAD

**Issue by bramus** [bramus/react-native-maps-directions#80]
It's been a while since I've done a new release. With a few PR's merged I've decided to first release the next version (`1.7.0`) as a beta (e.g. `1.7.0-beta.0`). If some of you can test/verify this release I'd be grateful. Once verified I'll release it as `1.7.0`.

**Comment by bramus** [comment]
New beta version `1.7.0-beta.1` published. Contains an updated `index.d.ts` file, as per https://github.com/bramus/react-native-maps-directions/pull/81

**Comment by methodbox** [comment]
If you want to add me on this I think I'll be able to test it tonight.

**Comment by methodbox** [comment]
I used this in testing for two hours last night in an Expo project with no issue. I haven't setup any official smoke or unit tests, but the only errors I received were due to my own API settings.

**Comment by bramus** [comment]
1.7.0 released, thanks for your input :)
