### ISSUE TITLE
[Request] Component receiving overview_polyline

### ISSUE THREAD

**Issue by NelsonPRSousa** [bramus/react-native-maps-directions#82]
Hi guys,
Thank you for your hard work with this library!

Do you think it will be possible to simplify MapViewDirections component? The main goal was to create a simpler component that just receives the data returned by Google Directions API. With this, we could use this library when that call to Google Directions API is made through a back-end service.

Correct me if I am wrong, but currently the workflow of this lib is:
1. Provide origin
2. Provide destination
3. Provide Google API Key
4. Fetch results from Google Directions API
5. Decode polyline points
6. Render the route

What if the results from Google Directions API came from a back-end solution? Could it be possible to "delivery" this results (encoded or decoded) to this library?

You guys rock! 👍

**Comment by bramus** [comment]
If you're looking for a component that draws a given polyline, then use `MapView.Polyline` itself. This library here is a wrapper around it that fetches data from Google Maps Directions' API, and then builds up the data needed for the `MapView.Polyline`.

You could do one of these:

1. Write a component yourself that fetches the data from your endpoint and passes it onto `MapView.Polyline`
2. Use the `directionsServiceBaseUrl` prop to override the endpoint which is accessed for the data. Whilst this works it does require that your endpoint returns the same data format as Google Maps Directions' API does.

Elaborating further on point 2: Ideally a change into `react-native-maps-directions` would be made that allows one to pass in a translation function, which translates the returned JSON into the data needed for the `MapView.Polyline`. I'll happily accept and merge a PR which provides this.
