### ISSUE TITLE
Proposal: Pull API key from app.json / share with react-native-maps

### ISSUE THREAD

**Issue by methodbox** [bramus/react-native-maps-directions#84]
Using the API key as a prop presents obvious security issues. The key should be able to be pulled from `app.json` just as with `react-native-maps`.

I have a feeling this isn't something that is easy to do, but as it is currently it presents an issue that controls on the API key associated with things like the `bundleIdentifier` probably don't work as expected.

The best solution I can conceive is not making the prop required and using it from a dependency from `react-native-maps`, since this is required anyway.

I'm going to experiment with this on my own and I believe that as long as `MapView` (or another component which relies on an API key) is part of _your_ component and wraps `MapViewDirections` it shouldn't be necessary to use the key directly.

Obviously, this means a bit of a rewrite on `react-native-maps-directions` to not request the key, but there must be some way to code around it.

**Comment by methodbox** [comment]
Thanks to an issue I opened at `expo`, I've discovered a way to solve this for Expo, at least. You use the Expo `Constants`.

```ts
_onPressTest = (): void => {
    const test = Constants.manifest.ios.config.googleMapsApiKey;
    console.log(test);
  };
```

So this would require native code to be configured to export the constants, but I'm gonna guess that `react-native-maps` is already doing this; there is probably a way we could just hook into that such that we import some kind of dependency of their's.

Here is how the RN docs explain it:  https://facebook.github.io/react-native/docs/native-modules-ios#exporting-constants

**Comment by methodbox** [comment]
I'm not sure how much more secure this would be, but it would certainly be more secure that no restriction, but this user on StackOverflow makes a good point:

https://stackoverflow.com/questions/52509599/how-does-googles-api-key-restrictions-work-for-mobile-apps?rq=1

As long as the `bundleIdentifier` is in the JSON header request, then it can be found.

The best solution is probably not requesting the API key at all and instead sending this request to your own external API on a server, securely and restricted, then making the request from there; only an authorized app could do this.

However, that still doesn't prevent a very determined hacker from just installing the app, then observing the request and attempting to sniff it, but that's a lot harder and more involved that reverse dumping an Android app.

**Comment by methodbox** [comment]
The best solution I've come up with so far is this.

I built a simple Express API to handle the "backend" API request; this would feasibly run from my cloud server and act as a proxy between Google and my app, allowing my to hide my API key and the app to be none the wiser. I haven't experimented with this adjustment to `react-native-maps` but I'll try that next; I'm sure it will work as it's so simple.

TS was driving me crazy, so this just JS for now, but it would be worth considering that TS would allow sanitizing the types that are returned for the API values before putting that burden on the app.

```js
const express = require('express');
const fetch = require('node-fetch');
const queryString = require('querystring');
const app = express();
const apiKey = '***redacted Google API key';

const queryDirections = url => {};
app.get('/', (req, res) => {
  req.query.key = apiKey;
  const encodedQuery = queryString.encode(req.query);
 
  fetch(`https://maps.googleapis.com/maps/api/directions/json?${encodedQuery}${apiKey}`)
    .then(res => res.json())
    .then(json => {
      return res.send(json);
    });
});

app.listen(5000);
```

And then in my module, to test locally:

```ts
    <MapViewDirections
        directionsServiceBaseUrl="http://192.168.1.133:5000/"
        region="US"
        origin={this.state.startMarker}
        destination={this.state.endMarker}
        apikey="placeholder"
        strokeWidth={5}
        strokeColor="blue"
    />
```

**Comment by methodbox** [comment]
For what it's worth, this solution also obscures the API key from server logs:

```bash
xx.xx.xx.xx - - [20/May/2019:02:59:28 +0000] "GET /api/?origin=37.78825,-122.4324&waypoints=&destination=37.7882987795,-122.42243453&**key=placeholder**&mode=driving&language=en&region=US HTTP/1.1" 200 2138 "-" "Expo/2.10.0.105122 CFNetwork/978.0.7 Darwin/18.5.0"
```

**Comment by bramus** [comment]
Thanks for your report and follow-up. I'm closing this issue, as:

- `app.json` is something specific to Expo, and not React Native in itself.
- The `MapViewDirections` component itself does not store the API key — It only gets it injected at runtime through a prop.

As a user of this component you can decide yourself where you want to store it. Be it in `app.json`, a config-file using `react-native-config`, an API call to your own API that you do upfront, etc. Securing those locations falls outside the scope of `react-native-maps-directions`.

**Comment by chinalwb** [comment]
5 ys later, it is still a good one to comment.

That the best practice is to refactor this library to add an option to load Directions Data from developer's own backend.
say, introduce a new parameter for customized request for fetching the Directions data, then consume it as of how we do it now.

This would be a much safer way.

**Comment by chinalwb** [comment]
I had an update based on this awesome library.

https://github.com/chinalwb/react-native-maps-directions-via-server

It moved the `apikey` from app side to server side, by removing `apikey` from the library and marked `directionsServiceBaseUrl` as a required param.
