### ISSUE TITLE
Making directions centered in the screen

### ISSUE THREAD

**Issue by barakoles** [bramus/react-native-maps-directions#88]
Hi, whenever I get two locations, I was able to figure it out a `latitudeDelta` and `longitudeDelta` quotient with the `distance`. Then, I'd like to know if anyone knows how would I make the entire route centered in the screen. Atm, only the start location is centered

**Comment by bramus** [comment]
This is covered in the README, in the [extended example section](https://github.com/bramus/react-native-maps-directions#extended-example).
