### ISSUE TITLE
Error on GMAPS route request

### ISSUE THREAD

**Issue by jose920405** [bramus/react-native-maps-directions#89]
I'm running in ios and currently i have created the apiKey and all needed **APIs** enabled.

![Screen Shot 2019-06-19 at 2 10 27 PM](https://user-images.githubusercontent.com/12536184/59793456-3a2b9900-929c-11e9-9dcd-e83eb81220c8.png)

And i'm having the next warning in the ios simulator.

```
'react-native-maps-directions Error on GMAPS route request', 'This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxx.52.249.xxxx, with empty referer'
```

**Code:**

```
const origin = { latitude: 3.367857, longitude: -76.531143 };
const destination = { latitude: 3.366294, longitude: -76.531968 };

<MapViewDirections
  origin={origin}
  destination={destination}
  apikey={'MyApiKey'}
/>
```

I was thinking that maybe is related with `Application restrictions` and for test i selected `none` and works 😕 . I think that i have the correct configuration because i did put a rule for specific **bundle identifier**

![Screen Shot 2019-06-19 at 2 53 57 PM](https://user-images.githubusercontent.com/12536184/59796897-208e4f80-92a4-11e9-9265-d21fb798b05c.png)

So, the question is

use `none` is correct? because i think that if you want apply restriction the correct way is select more that one or have an option with something like `Restrict All EXCEPT` and selects the exception.

**Version Information:**

```
"react-native-maps": "0.24.2",
"react-native-maps-directions": "1.7.0",
```

______

```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
      Memory: 25.46 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

**Comment by bramus** [comment]
Setting the limitation to `none` is not recommended, as that will allow anyone to use your API key if they were to get their hands on it.

Limiting it to a platform is a good practice (and limiting the bundle identifier is even better).
If you're building for both Android and iOS (which you most likely are), then register two API keys. Using [`Platform.OS`](https://facebook.github.io/react-native/docs/platform-specific-code#platform-module) you can then choose which key to use.

Please refer to Google's own [API Key Best Practices](https://developers.google.com/maps/api-key-best-practices) for a full writeup on this subject.

I'm marking this issue as invalid as it's not an issue bound to react-native-maps-directions but to the configuration of Google's API Services. Don't hesitate to add more replies to this thread.

**Comment by michele-ruocco** [comment]
I am getting this problem when I start my app on iOS despite having properly configured api key restrictions with the app bundle on Google Cloud. Do you have any feedbacks @jose920405 ?
