### ISSUE TITLE
react-native-maps-directions Error on GMAPS route request, Unknown error

### ISSUE THREAD

**Issue by rungwe** [bramus/react-native-maps-directions#94]
```
let destination = { latitude: stand.latitude, longitude: stand.longitude };
let origin = { latitude: location.coords.latitude, longitude: location.coords.latitude };
return(
<MapView
              style={{ flex: 1 }}
              initialRegion={{
                latitude: location.coords.latitude,
                longitude: location.coords.longitude,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}
            >
              <MapViewDirections
                origin={origin}
                destination={destination}
                apikey={GOOGLE_MAPS_APIKEY}
              />
            </MapView>);
```

Above is a snippet of my code, I am getting this error, 
react-native-maps-directions Error on GMAPS route request, Unknown error

I am running my application on expo on an ios device, is there I am doing wrong?

I have checked my google keys, they are active and well

**Comment by StefanDorresteijn** [comment]
Might be because your origin has latitude and longitude set to `location.coords.longitude`

**Comment by bramus** [comment]
Can you check the output of the API request? It should provided you with more info …

**Comment by RohitHegde44** [comment]
Did you set up Google Maps for IOS
It uses Apple Maps by default

**Comment by bytesk** [comment]
i get warning to "Error on GMAPS route request" 
but, if i try from "https://maps.googleapis.com/maps/api/directions/json" with my api key, and works, 

but from react-native-maps-directions i get warning "Error on GMAPS route request" 

and how to solve it? 

i'm done with billing in google console

@bramus please help this

**Comment by bramus** [comment]
Did you set [the proper restrictions](https://developers.google.com/maps/documentation/ios-sdk/get-api-key#restrict_key)? You can test with an unrestricted API key, and then try to restrict it further down so that it cannot be used outside of an Android/iOS app.

**Comment by bytesk** [comment]
Yes of course, i'm done with restrict and not restrict but not work. And i'm implement to add sha1 from android keystore to google console and not work to. And how? Last month from my project work fine. But now not work and now i change api key google from last month work. 

Sorry for my bad english, but help this problem pleasee @bramus

**Comment by bramus** [comment]
Did you [enable billing](https://developers.google.com/maps/gmp-get-started#create-billing-account) for your account?

Typically the error message will provide extra info like that right after "Error on GMAPS route request", for example:

<img width="542" alt="Screenshot 2019-08-28 at 22 56 23" src="https://user-images.githubusercontent.com/213073/63892110-1b0d5e00-c9e7-11e9-95e7-c84255713fb0.png">

**Comment by bytesk** [comment]
yes of course, i'm done enable billing google cloud, and then same not work still warning "Error on GMAPS route request", and how? @bramus

**Comment by bytesk** [comment]
@bramus can u give yourr api key just for test? after that u can remove or regenerate your api key,
i dont know, why didnwork for me, i done enable billing google cloud,

**Comment by bramus** [comment]
> can u give yourr api key just for test? 
Sorry but no can do …

To test if your API key works fine from within an app, try testing with a fixed input for the `origin` and `destination` props. You can check [the example](https://github.com/bramus/react-native-maps-directions#basic-usage) for this.

If that is the case then the problem resides in your code somewhere. It could be that the format of `origin`/`destination` is wrong, or that it's contents are invalid. What exactly are you trying to insert into it @bytesk (same goes for OP @rungwe)?

**Comment by bytesk** [comment]
![Untitled](https://user-images.githubusercontent.com/36951004/63924839-37ef7300-ca73-11e9-8faa-74e0b9b9ec45.png)

still dont work, and get this warning bro? @bramus 
any solution?

**Comment by bramus** [comment]
My apps that have react-native-maps-directions integrated still work fine.

As mentioned above I think there's a problem with the values that you're setting for the `origin`/`destination` props. Please check those. Try with a value that's known to work first (see [example](https://github.com/bramus/react-native-maps-directions#basic-usage)).

And oh, please, don't "bro" me ;)

**Comment by bytesk** [comment]
still dont work i'm trying with example code @bramus 

sorry for that "bro" hahaha lol 

can i know , u use react-native-maps version? and react-native-maps-directions version? and react-native version? 

and u use install package with yarn or npm?

**Comment by bytesk** [comment]
i'm trying with new project react native in version 0.60 and still working
whats wrong in my project? in react native version 0.57.7? 
huah i dont know why get this error warning "error on GMAPS"

**Comment by bramus** [comment]
I've got a RN 0.57.4 app (with react-native-maps 0.22.1) in production that's working. Yesterday I started a new RN 0.60.5 app (with react-native-maps 0.25) and that's also working.

I re-test my example with RN 0.57.7 (with react-native-maps 0.25) and it's also working fine. I've also published this example app (with said RN version) in a separate repository: https://github.com/bramus/react-native-maps-directions-example

This, again, leaves me to the conclusion that there's either something wrong with:

- The input you pass into `origin`/`destination` props
- The configuration of your API Key

I'm therefore labeling this issue as invalid (as it's not a `react-native-maps-directions` bug/issue). I'm also closing this issue, but don't let that stop the conversation here.

**Comment by bytesk** [comment]
big noo wrong with input into origin / destination, because in my fresh project react native version 0.60 still working,

maybe my project have litle problem, and i dont know why,

i want research again 

but, thankyou @bramus for your feedback, and for your fast response to me

**Comment by IgorDePaula** [comment]
I have the same error, Mey api key has credit card put on account of google, all right, but I received the same error.

**Comment by chanthea** [comment]
Well, i have the same experience. I noticed that i only have this problem when i enabled debug-mode, when i disabled it, it worked like charms.

**Comment by IgorDePaula** [comment]
I discovery the error: when initially the apps not got the primary position of user, the component not got trace route

**Comment by Bsingh2697** [comment]
Yup Found the solution, u guys might me using coordinates for the places where there is no land route.

**Comment by aithashi** [comment]
Hi 
is there a way we could catch these kind of errors/warning so that we can handle accordingly in mobile client?

**Comment by audrew** [comment]
add property ``` lineDashPattern={[0]} ```

**Comment by davmaene** [comment]
> add property `lineDashPattern={[0]}`

this works for me, thanks you save my day
