### ISSUE TITLE
How can i show data in a small information window attached to the route in MapViewDirection?

### ISSUE THREAD

**Issue by RohitHegde44** [bramus/react-native-maps-directions#96]
I would like to show Information like Distance and time required in a small window (or pop-up like design) for the route displayed using MapViewDirection

**Comment by bramus** [comment]
You can use the `onReady` callback to read info from the directions rendered, and then use those in your floating window / popup.

**Comment by vineethvijayan** [comment]
Can you please provide an example of how you added a floating window/popup on google maps?
